11-19 Email
CHTC/chtc-website-source pull request #164
Opened 2020-11-19 20:17 UTC by EUdds

2020-11-19 20:22 UTC, jmvera255 requested changes
please remove office hours link, we don't want the link posted publicly

2020-11-20 02:43 UTC, EUdds commented
@jmvera255 done!

2020-11-20 16:14 UTC, ChristinaLK approved these changes

2020-11-20 16:20 UTC, jmvera255 approved these changes

2020-11-20 16:21 UTC, merged