minor changes to bring docs up to date with new config
CHTC/chtc-website-source pull request #171
Opened 2020-12-21 15:40 UTC by ChristinaLK

- adding login node info to hpc overview
- deleting note about new cluster
- changing default cpu request to 20 cores per node

2020-12-21 20:29 UTC, jmvera255 requested changes
one minor change requested

2020-12-21 20:29 UTC, jmvera255 commented on hpc-job-submission.md
> +#SBATCH --partition=univ2       # default "univ", if not specified
comment still needs to be changed 
`#default "univ2"`

2020-12-21 20:31 UTC, jmvera255 commented on hpc-job-submission.md
> +#SBATCH --partition=univ2       # default "univ", if not specified
```suggestion
#SBATCH --partition=univ2       # default "univ2", if not specified
```

2021-01-04 20:10 UTC, jmvera255 submitted a review, later dismissed

2021-01-04 20:21 UTC, jmvera255 approved these changes
@ChristinaLK I caught a few more `univ` specifics that I changed to `univ2` in additional commits

2021-01-04 20:23 UTC, ChristinaLK commented
perfect, thanks.

2021-01-04 20:23 UTC, merged