clarify IsBuildJob
CHTC/chtc-website-source pull request #266
Opened 2021-07-20 17:00 UTC by lmichael107

2021-07-20 17:08 UTC, lmichael107 commented
@ChristinaLK @agitter either of you could review and merge, given Trent Prall's recent confusion.

2021-07-20 21:30 UTC, agitter requested changes
This is a helpful addition and would have addressed the recent confusion we saw about build servers.

I corrected one typo but otherwise approve.

2021-07-20 21:30 UTC, agitter commented on inter-submit.md
> +Note that you'll want to use `+IsBuildJob = true` to specifically match to CHTC's servers designated for compiling code (which include Matlab compilers and other compilin tools you may need). Compili
```suggestion
Note that you'll want to use `+IsBuildJob = true` to specifically match to CHTC's servers designated for compiling code (which include Matlab compilers and other compiling tools you may need). Compiling servers do not include specialized resources like GPUs, extreme amounts of RAM/disk, etc.; to build/test software in these cases, submit an interactive job without `+IsBuildJob`.
```

2021-07-21 14:11 UTC, lmichael107 commented on inter-submit.md
> +Note that you'll want to use `+IsBuildJob = true` to specifically match to CHTC's servers designated for compiling code (which include Matlab compilers and other compilin tools you may need). Compili
thanks for the typo catch!

2021-07-21 14:13 UTC, ChristinaLK approved these changes

2021-07-21 14:13 UTC, merged