rough draft of singularity in htc guide
CHTC/chtc-website-source pull request #312
Opened 2021-10-12 21:02 UTC by ChristinaLK

Needs review for
- whether the instructions are accurate @jasoncpatton 
- the recommendations for transfer/squid/staging are what we want @lmichael107 @bbockelm 
- formatting and un-broken links @CannonLock

2021-10-15 19:40 UTC, CannonLock requested changes

2021-10-15 19:40 UTC, CannonLock commented on uw-research-computing/singularity-htc.md
> +	provided on DockerHub](https://hub.docker.com/r/fenicsproject/stable),
This link is broken.

2021-11-10 20:11 UTC, ChristinaLK reviewed
changing image file extension

2021-11-10 20:11 UTC, ChristinaLK commented on uw-research-computing/singularity-htc.md
> +	[alice@build]$ singularity build /software/alice/name.simg docker://user/image:version
```suggestion
	[alice@build]$ singularity build /software/alice/name.sif docker://user/image:version
```

2021-11-10 20:11 UTC, ChristinaLK commented on uw-research-computing/singularity-htc.md
> +	and save it to a file named `fenics.simg`, she would run:
```suggestion
	and save it to a file named `fenics.sif`, she would run:
```

2021-11-10 20:11 UTC, ChristinaLK commented on uw-research-computing/singularity-htc.md
> +	[alice@build]$ singularity build /software/alice/fenics.simg docker://fenicsproject/stable:latest
```suggestion
	[alice@build]$ singularity build /software/alice/fenics.sif docker://fenicsproject/stable:latest
```

2021-11-10 20:11 UTC, ChristinaLK commented on uw-research-computing/singularity-htc.md
> +transfer_input_files = image.simg
```suggestion
transfer_input_files = image.sif
```

2021-11-10 20:11 UTC, ChristinaLK commented on uw-research-computing/singularity-htc.md
> ++SingularityImage = "./image.simg"
```suggestion
+SingularityImage = "./image.sif"
```

2021-11-10 20:11 UTC, ChristinaLK commented on uw-research-computing/singularity-htc.md
> +transfer_input_files = http://proxy.chtc.wisc.edu/SQUID/user/image.simg
```suggestion
transfer_input_files = http://proxy.chtc.wisc.edu/SQUID/user/image.sif
```

2021-11-10 20:11 UTC, ChristinaLK commented on uw-research-computing/singularity-htc.md
> ++SingularityImage = "./image.simg"
```suggestion
+SingularityImage = "./image.sif"
```

2021-11-10 20:11 UTC, ChristinaLK commented on uw-research-computing/singularity-htc.md
> ++SingularityImage = "/software/user/image.simg"
```suggestion
+SingularityImage = "/software/user/image.sif"
```

2021-12-27 21:25 UTC, ChristinaLK commented
This should now be ready to merge except that it's out of date because of container universe. 😭 
Will revisit after new years.

2023-04-28 21:18 UTC, aowen-uwmad commented
This PR is obsolete after #582

2023-04-28 21:18 UTC, closed without merging