making flocking and gliding more open
CHTC/chtc-website-source pull request #337
Opened 2021-11-24 18:18 UTC by ChristinaLK

2021-11-24 18:19 UTC, ChristinaLK commented on uw-research-computing/scaling-htc.md
> +addition to what\'s already available in CHTC, including specialized
```suggestion
in addition to what\'s already available in CHTC, including specialized 
```

2021-11-24 18:19 UTC, ChristinaLK commented on uw-research-computing/scaling-htc.md
> +    resource, please [contact us](chtc@cs.wisc.edu)!  In certain cases, we may be
```suggestion
    resources, please [contact us](chtc@cs.wisc.edu)!  In certain cases, we may be 
```

2021-12-27 19:33 UTC, lmichael107 requested changes

2021-12-27 19:33 UTC, lmichael107 commented on uw-research-computing/scaling-htc.md
> +We call sending jobs to other institutions in our OSG pool *gliding*.
```suggestion
When you send jobs to other institutions in our OSG pool, we call that *gliding*.
```

2021-12-27 19:33 UTC, lmichael107 commented on uw-research-computing/scaling-htc.md
> +B. OSG Pool
```suggestion
B. UW-Madison's OSG Pool
```

2021-12-27 20:48 UTC, ChristinaLK commented on uw-research-computing/scaling-htc.md
> +the [Open Science Pool](https://osg-htc.org/about/open_science_pool/) associated with that submission point. This OSG pool is the
Nope, this is from when Cannon purged Open Science Grid from the website four months ago.

2021-12-27 20:50 UTC, ChristinaLK commented on uw-research-computing/scaling-htc.md
> +    in your home directory and/or in SQUID (the options listed on our [file
yes, and my latest changes should have that information.

2021-12-27 20:52 UTC, ChristinaLK commented
@lmichael107 it looks like you might have seen an older version of this PR when reviewing. I incorporated most of your suggestions - can you give it one more once-over?

2022-02-25 23:30 UTC, merged