updating lots of transition docs
CHTC/chtc-website-source pull request #619
Opened 2023-09-13 20:23 UTC by ChristinaLK

2023-09-14 16:57 UTC, aowen-uwmad requested changes

2023-09-14 16:57 UTC, aowen-uwmad commented on _uw-research-computing/archived/hpc-transition-2023.md
I'm not sure how this will behave for linking from the main guides page. I think the `guide:` section may still register but I don't know where it will end up since the tag and category is removed. I think this needs to be previewed before merging.

2023-09-14 16:57 UTC, aowen-uwmad commented on _uw-research-computing/os-transition-htc.md
> +title: Using Custom Linx Versions in CHTC
```suggestion
title: Using Custom Linux Versions in CHTC
```
Misspelled "Linux"

2023-09-21 19:05 UTC, ChristinaLK commented
https://chtc.github.io/web-preview/preview-update-transitions

2023-09-21 19:40 UTC, ChristinaLK commented on _uw-research-computing/archived/hpc-transition-2023.md
https://chtc.github.io/web-preview/preview-update-transitions/uw-research-computing/guides.html

2023-09-22 19:28 UTC, aowen-uwmad commented on _uw-research-computing/archived/hpc-transition-2023.md
Looks good.

2023-09-22 19:32 UTC, aowen-uwmad approved these changes

2023-09-22 19:32 UTC, merged