Preview software overview
CHTC/chtc-website-source pull request #769
Opened 2024-06-04 14:21 UTC by mollymccarthy03

2024-06-04 14:25 UTC, mollymccarthy03 commented
https://chtc.github.io/web-preview/preview-molly-software-overview

2024-06-05 15:40 UTC, CannonLock requested changes
Looks good, just one tweak to make sure that any new guides are automatically added.

2024-06-05 15:40 UTC, CannonLock commented on _uw-research-computing/software-overview-htc.md
> +    <button class="btn btn-guide mb-lg-0 active" onclick="showExcerpt('running-python-jobs', 'side-divider')"><img src="/uw-research-computing/guide-icons/python-icon.png" alt="pythonlogo"> Python</b
@mollymccarthy03 Can you make this generated based on the link like you did below?

2024-06-05 15:46 UTC, CannonLock commented on _uw-research-computing/software-overview-htc.md
> +    <button class="btn btn-guide mb-lg-0 active" onclick="showExcerpt('running-python-jobs', 'side-divider')"><img src="/uw-research-computing/guide-icons/python-icon.png" alt="pythonlogo"> Python</b
I note that you need that icon url. I would suggest that rather then checking for `link == 'software'` you populate a `software_icon` with the url and check that the software_icon value is filled in instead. That way you can kill two birds with one key-value pair.

2024-08-20 16:40 UTC, merged